/**
 * Complete genogram sample data model
 * Contains 52 family members across multiple generations
 * Bill (key 4) is the proband - the focal individual for the genetic study
 */
export const genogramData = {
  "class": "GraphLinksModel",
  "copiesArrays": true,
  "pointsDigits": 1,
  "linkLabelKeysProperty": "labelKeys",
  "modelData": { "proband": 4 },
  "nodeDataArray": [
    { "key": 0, "name": "Aaron", "sex": "M", "mother": -10, "father": -11, "birth": "", "death": "", "note": "", "a": ["A123", "B74", "D85", "G4"] },
    { "key": 1, "name": "Alice", "sex": "F", "mother": -12, "father": -13, "birth": "", "death": "", "note": "", "a": ["B74", "C12", "D85", "V4"] },
    { "key": 2, "name": "Bob", "sex": "M", "mother": 1, "father": 0, "birth": "", "death": "", "note": "", "a": ["E92", "F4"] },
    { "key": 3, "name": "Barbara", "sex": "F", "mother": "", "father": "", "birth": "", "death": "", "note": "", "a": ["D99", "M23"] },
    { "key": 4, "name": "Bill", "sex": "M", "mother": 1, "father": 0, "birth": "", "death": "", "note": "", "a": ["A6", "B3"] },
    { "key": 5, "name": "Brooke", "sex": "F", "mother": "", "father": "", "birth": "", "death": "", "note": "", "a": ["A2"] },
    { "key": 6, "name": "Claire", "sex": "F", "mother": 1, "father": 0, "birth": "", "death": "", "note": "", "a": ["B34", "G4"] },
    { "key": 7, "name": "Carol", "sex": "F", "mother": 1, "father": 0, "birth": "", "death": "", "note": "", "a": ["C23123", "G4"] },
    { "key": 8, "name": "Chloe", "sex": "F", "mother": 1, "father": 0, "birth": "", "death": "", "note": "", "a": ["A123", "Dev97", "G4"] },
    { "key": 9, "name": "Chris", "sex": "M", "mother": "", "father": "", "birth": "", "death": "", "note": "", "a": ["C23123", "E234", "H54"] },
    { "key": 10, "name": "Ellie", "sex": "F", "mother": 3, "father": 2, "birth": "", "death": "", "note": "", "a": ["D99", "F4", "G0594"] },
    { "key": 11, "name": "Dan", "sex": "M", "mother": 3, "father": 2, "birth": "", "death": "", "note": "", "a": ["F4", "G1212"] },
    { "key": 12, "name": "Elizabeth", "sex": "F", "mother": "", "father": "", "birth": "", "death": "", "note": "", "a": ["H"] },
    { "key": 13, "name": "David", "sex": "M", "mother": 5, "father": 4, "birth": "", "death": "", "note": "", "a": ["A2342", "B3"] },
    { "key": 14, "name": "Emma", "sex": "F", "mother": 5, "father": 4, "birth": "", "multiple": 3, "death": "", "note": "", "a": ["B3"] },
    { "key": 80, "name": "Diana", "sex": "F", "mother": 5, "father": 4, "birth": "", "multiple": 3, "identical": 14, "death": "", "note": "", "a": ["B3", "A45"] },
    { "key": 15, "name": "Evan", "sex": "M", "mother": 8, "father": 9, "birth": "", "multiple": 4, "death": "", "note": "", "a": ["A123", "CV9569"] },
    { "key": 16, "name": "Ethan", "sex": "M", "mother": 8, "father": 9, "birth": "", "multiple": 4, "identical": 15, "death": "", "note": "", "a": ["A123", "D343", "G4"] },
    { "key": 17, "name": "Eve", "sex": "F", "mother": "", "father": "", "birth": "", "death": "", "note": "", "a": ["E509468"] },
    { "key": 18, "name": "Emily", "sex": "F", "mother": 8, "father": 9, "birth": "", "death": "", "note": "", "a": ["F68", "G", "H"] },
    { "key": 19, "name": "Fred", "sex": "M", "mother": 17, "father": 16, "birth": "", "multiple": 5, "death": "", "note": "", "a": ["C56", "G345834058"] },
    { "key": 20, "name": "Faith", "sex": "F", "mother": 17, "father": 16, "birth": "", "multiple": 5, "death": "", "note": "", "a": ["H0452-a"] },
    { "key": 21, "name": "Felicia", "sex": "F", "mother": 12, "father": 13, "birth": "", "death": "", "note": "", "a": ["B3", "A549"] },
    { "key": 22, "name": "Frank", "sex": "M", "mother": 12, "father": 13, "birth": "", "death": "", "note": "", "a": ["B349058", "E867"] },
    { "key": 23, "name": "Castor", "sex": "?", "mother": 12, "father": 13, "birth": "", "death": true, "reproduction": "MC", "note": "", "a": ["B3", "C23"] },
    { "key": 24, "name": "Nestor", "sex": "?", "mother": 12, "father": 13, "birth": "", "death": true, "reproduction": "T", "note": "", "a": ["D456"] },
    { "key": 27, "name": "Flora", "sex": "F", "mother": 12, "father": 13, "adopted": "in", "birth": "", "death": "", "note": "", "a": ["E766"] },
    { "key": 28, "name": "Aurora", "sex": "F", "mother": 12, "father": 13, "adopted": "out", "birth": "", "death": "", "note": "", "a": ["B3", "F345"] },
    { "key": 70, "name": "Elsbeth", "sex": "F", "mother": 3, "father": 2, "birth": "", "multiple": 1, "death": "", "note": "", "a": ["F4", "D99", "G0584"] },
    { "key": 71, "name": "Daneel", "sex": "M", "mother": 3, "father": 2, "birth": "", "multiple": 1, "death": "", "note": "", "a": ["F4", "G4", "H567"] },
    { "key": 72, "name": "Tweedledee", "sex": "M", "mother": 3, "father": 2, "birth": "", "multiple": 2, "death": "", "note": "", "a": ["F4", "A37"] },
    { "key": 73, "name": "Tweedledum", "sex": "M", "mother": 3, "father": 2, "birth": "", "multiple": 2, "identical": 72, "death": "", "note": "", "a": ["F4", "B54"] },
    { "key": 74, "name": "Tweedledoe", "sex": "F", "mother": 3, "father": 2, "birth": "", "multiple": 2, "death": "", "note": "", "a": ["F4", "D99", "C305"] },
    { "key": -10, "name": "Paternal Grandfather", "sex": "M", "mother": -33, "father": -32, "birth": "", "death": true, "note": "", "a": ["D02934", "G4"] },
    { "key": -11, "name": "Paternal Grandmother", "sex": "F", "mother": "", "father": "", "birth": "", "death": true, "note": "", "a": ["E5690"] },
    { "key": -32, "name": "Paternal Great", "sex": "M", "mother": "", "father": "", "birth": "", "death": true, "note": "", "a": ["F0834"] },
    { "key": -33, "name": "Paternal Great", "sex": "F", "mother": "", "father": "", "birth": "", "death": true, "note": "", "a": ["G294"] },
    { "key": -40, "name": "Great Uncle", "sex": "M", "mother": -33, "father": -32, "birth": "", "death": true, "note": "", "a": ["H45069", "G4"] },
    { "key": -41, "name": "Great Aunt", "sex": "F", "mother": -33, "father": -32, "birth": "", "death": true, "note": "", "a": ["A2"] },
    { "key": -20, "name": "Uncle", "sex": "M", "mother": -11, "father": -10, "birth": "", "death": "", "note": "", "a": ["B5408", "G4"] },
    { "key": -12, "name": "Maternal Grandfather", "sex": "M", "mother": "", "father": "", "birth": "", "death": "", "note": "", "a": ["C23894"] },
    { "key": -13, "name": "Maternal Grandmother", "sex": "F", "mother": -31, "father": -30, "birth": "", "death": "", "note": "", "a": ["D23"] },
    { "key": -21, "name": "Aunt", "sex": "F", "mother": -13, "father": -12, "birth": "", "death": "", "note": "", "a": ["E3405"] },
    { "key": -22, "name": "Uncle", "sex": "M", "mother": "", "father": "", "birth": "", "death": "", "note": "", "a": ["F5408"] },
    { "key": -23, "name": "Cousin", "sex": "M", "mother": -21, "father": -22, "birth": "", "death": "", "note": "", "a": ["G2173"] },
    { "key": -30, "name": "Maternal Great", "sex": "M", "mother": "", "father": "", "birth": "", "death": true, "note": "", "a": ["H34"] },
    { "key": -31, "name": "Maternal Great", "sex": "F", "mother": -50, "father": -51, "birth": "", "death": true, "note": "", "a": ["A34"] },
    { "key": -42, "name": "Great Uncle", "sex": "M", "mother": -30, "father": -31, "birth": "", "death": true, "note": "", "a": ["B997"] },
    { "key": -43, "name": "Great Aunt", "sex": "F", "mother": -30, "father": -31, "birth": "", "death": "", "note": "", "a": ["C09568"] },
    { "key": -50, "name": "Maternal Great Great", "sex": "F", "mother": "", "father": "", "birth": "", "death": true, "note": "", "a": ["D68"] },
    { "key": -51, "name": "Maternal Great Great", "sex": "M", "mother": "", "father": "", "birth": "", "death": true, "note": "", "a": ["E568"] },
    { "category": "MateLabel", "key": -53 },
    { "category": "MateLabel", "key": -54 },
    { "category": "MateLabel", "key": -55 },
    { "category": "MateLabel", "key": -56 },
    { "category": "MateLabel", "key": -57 },
    { "category": "MateLabel", "key": -58 },
    { "category": "MateLabel", "key": -59 },
    { "category": "MateLabel", "key": -60 },
    { "category": "MateLabel", "key": -61 },
    { "category": "MateLabel", "key": -62 },
    { "category": "MateLabel", "key": -63 },
    { "category": "MateLabel", "key": -64 }
  ],
  "linkDataArray": [
    { "from": 0, "to": 1, "category": "Mate", "labelKeys": [-53], "divorced": false },
    { "from": 2, "to": 3, "category": "Mate", "labelKeys": [-54], "divorced": false },
    { "from": 4, "to": 5, "category": "Mate", "labelKeys": [-55], "divorced": false },
    { "from": 8, "to": 9, "category": "Mate", "labelKeys": [-56], "divorced": false },
    { "from": 12, "to": 13, "category": "Mate", "labelKeys": [-57], "divorced": false },
    { "from": 17, "to": 16, "category": "Mate", "labelKeys": [-58], "divorced": false },
    { "from": -10, "to": -11, "category": "Mate", "labelKeys": [-59], "divorced": false },
    { "from": -32, "to": -33, "category": "Mate", "labelKeys": [-60], "divorced": false },
    { "from": -12, "to": -13, "category": "Mate", "labelKeys": [-61], "divorced": false },
    { "from": -22, "to": -21, "category": "Mate", "labelKeys": [-62], "divorced": false },
    { "from": -30, "to": -31, "category": "Mate", "labelKeys": [-63], "divorced": false },
    { "from": -50, "to": -51, "category": "Mate", "labelKeys": [-64], "divorced": false },
    { "from": -59, "to": 0 },
    { "from": -61, "to": 1 },
    { "from": -53, "to": 2 },
    { "from": -53, "to": 4 },
    { "from": -53, "to": 6 },
    { "from": -53, "to": 7 },
    { "from": -53, "to": 8 },
    { "from": -54, "to": 10 },
    { "from": -54, "to": 11 },
    { "from": -55, "to": 13 },
    { "from": -55, "to": 14 },
    { "from": -55, "to": 80 },
    { "from": -56, "to": 15 },
    { "from": -56, "to": 16 },
    { "from": -56, "to": 18 },
    { "from": -58, "to": 19 },
    { "from": -58, "to": 20 },
    { "from": -57, "to": 21 },
    { "from": -57, "to": 22 },
    { "from": -57, "to": 23 },
    { "from": -57, "to": 24 },
    { "from": -57, "to": 27 },
    { "from": -57, "to": 28 },
    { "from": -54, "to": 70 },
    { "from": -54, "to": 71 },
    { "from": -54, "to": 72 },
    { "from": -54, "to": 73 },
    { "from": -54, "to": 74 },
    { "from": -60, "to": -10 },
    { "from": -60, "to": -40 },
    { "from": -60, "to": -41 },
    { "from": -59, "to": -20 },
    { "from": -63, "to": -13 },
    { "from": -61, "to": -21 },
    { "from": -62, "to": -23 },
    { "from": -64, "to": -31 },
    { "from": -63, "to": -42 },
    { "from": -63, "to": -43 }
  ]
};
